services:
  - type: web
    name: airflow
    env: docker
    dockerfilePath: src/Dockerfile    # if Dockerfile inside src folder
    buildContext: src                 # set build context to src folder
